unit Objekt.ExifPropertyTag;

interface

uses
  System.SysUtils, System.Types,  System.Classes, System.Variants, Objekt.ExifPropertyTagGPS;


type
  TExifPropertyTag = class
  private
    fAperture: string;
    fApertureValue: string;
    fArtist: string;
    fBitsPerSample: string;
    fBrightnessValue: string;
    fCfaPattern: string;
    fColorSpace: string;
    fComponentsConfiguration: string;
    fCompressedBitsPerSample: string;
    fCompression: string;
    fContrast: string;
    fCopyright: string;
    fCustomRendered: string;
    fDateTime: string;
    fDateTimeDigitized: string;
    fDateTimeOriginal: string;
    fDefaultCropSize: string;
    fDeviceSettingDescription: string;
    fDigitalZoomRatio: string;
    fDngVersion: string;
    fExifVersion: string;
    fExposureBiasValue: string;
    fExposureIndex: string;
    fExposureMode: string;
    fExposureProgram: string;
    fExposureTime: string;
    fFileSource: string;
    fFlash: string;
    fFlashPixVersion: string;
    fFlashEnergy: string;
    fFocalLength: string;
    fFocalLengthIn35mmFilm: string;
    fFocalPlaneResolutionUnit: string;
    fFocalPlaneXResolution: string;
    fFocalPlaneYResolution: string;
    fFNumber: string;
    fGainControl: string;
    fGPS: TExifPropertyTagGPS;
    fImageDescription: string;
    fImageLength: string;
    fImageUniqueId: string;
    fImageWidth: string;
    fInteroperabilityIndex: string;
    fISO: string;
    fISOSpeedRatings: string;
    fJpegInterchangeFormat: string;
    fJpegInterchangeFormatLength: string;
    fLightSource: string;
    fMake: string;
    fMakerNote: string;
    fMaxApertureValue: string;
    fMeteringMode: string;
    fModel: string;
    fNewSubfileType: string;
    fOecf: string;
    fOrfAspectFrame: string;
    fOrfPreviewImageLength: string;
    fOrfPreviewImageStart: string;
    fOrfThumbnailImage: string;
    fOrientation: string;
    fPhotometricInterpretation: string;
    fPixelXDimension: string;
    fPixelYDimension: string;
    fPlanarConfiguration: string;
    fPrimaryChromaticities: string;
    fReferenceBlackWhite: string;
    fRelatedSoundFile: string;
    fResolutionUnit: string;
    fRowsPerStrip: string;
    fRW2ISO: string;
    fRW2JpgFromRaw: string;
    fRW2SensorBottomBorder: string;
    fRW2SensorTopBorder: string;
    fRW2SensorLeftBorder: string;
    fRW2SensorRightBorder: string;
    fSamplesPerPixel: string;
    fSaturation: string;
    fSceneCaptureType: string;
    fSceneType: string;
    fSensingMethod: string;
    fSharpness: string;
    fShutterSpeedValue: string;
    fSoftware: string;
    fSpatialFrequencyResponse: string;
    fSpectralSenitivity: string;
    fStripByteCounts: string;
    fStripOffsets: string;
    fSubfileType: string;
    fSubjectArea: string;
    fSubjectDistance: string;
    fSubjectDistanceRange: string;
    fSubjectLocation: string;
    fSubsecTime: string;
    fSubsecTimeDigitized: string;
    fSubsecTimeOrig: string;
    fSubsecTimeDig: string;
    fSubsecTimeOriginal: string;
    fThumbnailImageLength: string;
    fThumbnailImageWidth: string;
    fUserComment: string;
    fYCbCrCoefficients: string;
    fWhiteBalance: string;
    fTransferFunction: string;
    fWhitePoint: string;
    fYCbCrPositioning: string;
    fYCbCrSubSampling: string;
    fXResolution: string;
    fYResolution: string;
public
    constructor Create;
    destructor Destroy; override;
    procedure Init;
    property Aperture: string read fAperture write fAperture;
    property ApertureValue: string read fApertureValue write fApertureValue;
    property Artist: string read fArtist write fArtist;
    property BitsPerSample: string read fBitsPerSample write fBitsPerSample;
    property BrightnessValue: string read fBrightnessValue write fBrightnessValue;
    property CfaPattern: string read fCfaPattern write fCfaPattern;
    property ColorSpace: string read fColorSpace write fColorSpace;
    property ComponentsConfiguration: string read  fComponentsConfiguration write fComponentsConfiguration;
    property CompressedBitsPerSample: string read fCompressedBitsPerSample write fCompressedBitsPerSample;
    property Compression: string read fCompression write fCompression;
    property Contrast: string read fContrast write fContrast;
    property Copyright: string read fCopyright write fCopyright;
    property CustomRendered: string read fCustomRendered write fCustomRendered;
    property DateTime: string read fDateTime write fDateTime;
    property DateTimeDigitized: string read fDateTimeDigitized write fDateTimeDigitized;
    property DateTimeOriginal: string read fDateTimeOriginal write fDateTimeOriginal;
    property DefaultCropSize: string read fDefaultCropSize write fDefaultCropSize;
    property DeviceSettingDescription: string read fDeviceSettingDescription write fDeviceSettingDescription;
    property DigitalZoomRatio: string read fDigitalZoomRatio write fDigitalZoomRatio;
    property DngVersion: string read fDngVersion write fDngVersion;
    property ExifVersion: string read fExifVersion write fExifVersion;
    property ExposureBiasValue: string read fExposureBiasValue write fExposureBiasValue;
    property ExposureIndex: string read fExposureIndex write fExposureIndex;
    property ExposureMode: string read fExposureMode write fExposureMode;
    property ExposureProgram: string read fExposureProgram write fExposureProgram;
    property ExposureTime: string read fExposureTime write fExposureTime;
    property FileSource: string read fFileSource write fFileSource;
    property Flash: string read fFlash write fFlash;
    property FlashPixVersion: string read fFlashPixVersion write fFlashPixVersion;
    property FlashEnergy: string read fFlashEnergy write fFlashEnergy;
    property FocalLength: string read fFocalLength write fFocalLength;
    property FocalLengthIn35mmFilm: string read fFocalLengthIn35mmFilm write fFocalLengthIn35mmFilm;
    property FocalPlaneResolutionUnit: string read fFocalPlaneResolutionUnit write fFocalPlaneResolutionUnit;
    property FocalPlaneXResolution: string read fFocalPlaneXResolution write fFocalPlaneXResolution;
    property FocalPlaneYResolution: string read fFocalPlaneYResolution write fFocalPlaneYResolution;
    property FNumber: string read fFNumber write fFNumber;
    property GainControl: string read fGainControl write fGainControl;
    property GPS: TExifPropertyTagGPS read fGPS write fGPS;
    property ImageDescription: string read fImageDescription write fImageDescription;
    property ImageLength: string read fImageLength write fImageLength;
    property ImageUniqueId: string read fImageUniqueId write fImageUniqueId;
    property ImageWidth: string read fImageWidth write fImageWidth;
    property InteroperabilityIndex: string read fInteroperabilityIndex write fInteroperabilityIndex;
    property ISO: string read fISO write fISO;
    property ISOSpeedRatings: string read fISOSpeedRatings write fISOSpeedRatings;
    property JpegInterchangeFormat: string read fJpegInterchangeFormat write fJpegInterchangeFormat;
    property JpegInterchangeFormatLength: string read fJpegInterchangeFormatLength write fJpegInterchangeFormatLength;
    property LightSource: string read fLightSource write fLightSource;
    property Make: string read fMake write fMake;
    property MakerNote: string read fMakerNote write fMakerNote;
    property MaxApertureValue: string read fMaxApertureValue write fMaxApertureValue;
    property MeteringMode: string read fMeteringMode write fMeteringMode;
    property Model: string read fModel write fModel;
    property NewSubfileType: string read fNewSubfileType write fNewSubfileType;
    property Oecf: string read fOecf write fOecf;
    property OrfAspectFrame: string read fOrfAspectFrame write fOrfAspectFrame;
    property OrfPreviewImageLength: string read fOrfPreviewImageLength write fOrfPreviewImageLength;
    property OrfPreviewImageStart: string read fOrfPreviewImageStart write fOrfPreviewImageStart;
    property OrfThumbnailImage: string read fOrfThumbnailImage write fOrfThumbnailImage;
    property Orientation: string read fOrientation write fOrientation;
    property PhotometricInterpretation: string read fPhotometricInterpretation write fPhotometricInterpretation;
    property PixelXDimension: string read fPixelXDimension write fPixelXDimension;
    property PixelYDimension: string read fPixelYDimension write fPixelYDimension;
    property PlanarConfiguration: string read fPlanarConfiguration write fPlanarConfiguration;
    property PrimaryChromaticities: string read fPrimaryChromaticities write fPrimaryChromaticities;
    property ReferenceBlackWhite: string read fReferenceBlackWhite write fReferenceBlackWhite;
    property RelatedSoundFile: string read fRelatedSoundFile write fRelatedSoundFile;
    property ResolutionUnit: string read fResolutionUnit write fResolutionUnit;
    property RowsPerStrip: string read fRowsPerStrip write fRowsPerStrip;
    property RW2ISO: string read fRW2ISO write fRW2ISO;
    property RW2JpgFromRaw: string read fRW2JpgFromRaw write fRW2JpgFromRaw;
    property RW2SensorBottomBorder: string read fRW2SensorBottomBorder write fRW2SensorBottomBorder;
    property RW2SensorLeftBorder: string read fRW2SensorLeftBorder write fRW2SensorLeftBorder;
    property RW2SensorRightBorder: string read fRW2SensorRightBorder write fRW2SensorRightBorder;
    property RW2SensorTopBorder: string read fRW2SensorTopBorder write fRW2SensorTopBorder;
    property SamplesPerPixel: string read fSamplesPerPixel write fSamplesPerPixel;
    property Saturation: string read fSaturation write fSaturation;
    property SceneCaptureType: string read fSceneCaptureType write fSceneCaptureType;
    property SceneType: string read fSceneType write fSceneType;
    property SensingMethod: string read fSensingMethod write fSensingMethod;
    property Sharpness: string read fSharpness write fSharpness;
    property ShutterSpeedValue: string read fShutterSpeedValue write fShutterSpeedValue;
    property Software: string read fSoftware write fSoftware;
    property SpatialFrequencyResponse: string read fSpatialFrequencyResponse write fSpatialFrequencyResponse;
    property SpectralSenitivity: string read fSpectralSenitivity write fSpectralSenitivity;
    property StripByteCounts: string read fStripByteCounts write fStripByteCounts;
    property StripOffsets: string read fStripOffsets write fStripOffsets;
    property SubfileType: string read fSubfileType write fSubfileType;
    property SubjectArea: string read fSubjectArea write fSubjectArea;
    property SubjectDistance: string read fSubjectDistance write fSubjectDistance;
    property SubjectDistanceRange: string read fSubjectDistanceRange write fSubjectDistanceRange;
    property SubjectLocation: string read fSubjectLocation write fSubjectLocation;
    property SubsecTime: string read fSubsecTime write fSubsecTime;
    property SubsecTimeDig: string read fSubsecTimeDig write fSubsecTimeDig;
    property SubsecTimeDigitized: string read fSubsecTimeDigitized write fSubsecTimeDigitized;
    property SubsecTimeOrig: string read fSubsecTimeOrig write fSubsecTimeOrig;
    property SubsecTimeOriginal: string read fSubsecTimeOriginal write fSubsecTimeOriginal;
    property ThumbnailImageLength: string read fThumbnailImageLength write fThumbnailImageLength;
    property ThumbnailImageWidth: string read fThumbnailImageWidth write fThumbnailImageWidth;
    property TransferFunction: string read fTransferFunction write fTransferFunction;
    property UserComment: string read fUserComment write fUserComment;
    property WhiteBalance: string read fWhiteBalance write fWhiteBalance;
    property WhitePoint: string read fWhitePoint write fWhitePoint;
    property XResolution: string read fXResolution write fXResolution;
    property YCbCrCoefficients: string read fYCbCrCoefficients write fYCbCrCoefficients;
    property YCbCrPositioning: string read fYCbCrPositioning write fYCbCrPositioning;
    property YCbCrSubSampling: string read fYCbCrSubSampling write fYCbCrSubSampling;
    property YResolution: string read fYResolution write fYResolution;
    procedure LoadTAGToStrings(aStrings: TStrings);

  end;



implementation

{ TExifPropertyTag }



constructor TExifPropertyTag.Create;
begin
  fGPS := TExifPropertyTagGPS.Create;
  Init;
end;

destructor TExifPropertyTag.Destroy;
begin
  FreeAndNil(fGPS);
  inherited;
end;

procedure TExifPropertyTag.Init;
begin
  fAperture        := '';
  fApertureValue   := '';
  fArtist          := '';
  fBitsPerSample   := '';
  fBrightnessValue := '';
  fCfaPattern      := '';
  fColorSpace      := '';
  fComponentsConfiguration := '';
  fCompressedBitsPerSample := '';
  fCompression := '';
  fContrast := '';
  fCopyright := '';
  fCustomRendered := '';
  fDateTime := '';
  fDateTimeDigitized := '';
  fDateTimeOriginal := '';
  fDefaultCropSize := '';
  fDeviceSettingDescription := '';
  fDigitalZoomRatio := '';
  fDngVersion := '';
  fExifVersion := '';
  fExposureBiasValue := '';
  fExposureIndex := '';
  fExposureMode := '';
  fExposureProgram := '';
  fExposureTime := '';
  fFileSource := '';
  fFlash := '';
  fFlashPixVersion := '';
  fFlashEnergy := '';
  fFocalLength := '';
  fFocalLengthIn35mmFilm := '';
  fFocalPlaneResolutionUnit := '';
  fFocalPlaneXResolution := '';
  fFocalPlaneYResolution := '';
  fFNumber := '';
  fGainControl := '';
  fImageDescription := '';
  fImageLength := '';
  fImageUniqueId := '';
  fImageWidth := '';
  fInteroperabilityIndex := '';
  fISO := '';
  fISOSpeedRatings := '';
  fJpegInterchangeFormat := '';
  fJpegInterchangeFormatLength := '';
  fLightSource := '';
  fMake := '';
  fMakerNote := '';
  fMaxApertureValue := '';
  fMeteringMode := '';
  fModel := '';
  fOecf := '';
  fOrfAspectFrame := '';
  fOrfPreviewImageLength := '';
  fOrfPreviewImageStart := '';
  fOrfThumbnailImage := '';
  fOrientation := '';
  fPhotometricInterpretation := '';
  fPixelXDimension := '';
  fPixelYDimension := '';
  fPlanarConfiguration := '';
  fPrimaryChromaticities := '';
  fReferenceBlackWhite := '';
  fRelatedSoundFile := '';
  fResolutionUnit := '';
  fRowsPerStrip := '';
  fRW2ISO := '';
  fRW2JpgFromRaw := '';
  fRW2SensorBottomBorder := '';
  fRW2SensorLeftBorder := '';
  fRW2SensorRightBorder := '';
  fRW2SensorTopBorder := '';
  fSamplesPerPixel := '';
  fSaturation := '';
  fSceneCaptureType := '';
  fSceneType := '';
  fSensingMethod := '';
  fSharpness := '';
  fShutterSpeedValue := '';
  fSoftware := '';
  fSpatialFrequencyResponse := '';
  fSubfileType := '';
  fSubjectArea := '';
  fSubjectDistance := '';
  fSubjectDistanceRange := '';
  fSubjectLocation := '';
  fSubsecTime := '';
  fSubsecTimeDigitized := '';
  fSubsecTimeOrig := '';
  fSubsecTimeDig  := '';
  fSubsecTimeOriginal := '';
  fThumbnailImageLength := '';
  fThumbnailImageWidth := '';
  fUserComment       := '';
  fYCbCrCoefficients := '';
  fWhiteBalance      := '';
  fTransferFunction  := '';
  fWhitePoint        := '';
  fYCbCrPositioning  := '';
  fYCbCrSubSampling  := '';
  fXResolution       := '';
  fYResolution       := '';
end;

procedure TExifPropertyTag.LoadTAGToStrings(aStrings: TStrings);
begin
  aStrings.Add('Aperture:       ' + fAperture);
  aStrings.Add('ApertureValue:  ' + fApertureValue);
  aStrings.Add('Artist:         ' + fArtist);
  aStrings.Add('BitsPerSample:  ' + fBitsPerSample);
  aStrings.Add('BrightnessValue: ' + fBrightnessValue);
  aStrings.Add('CfaPattern:      ' + fCfaPattern);
  aStrings.Add('ColorSpace:      ' + fColorSpace);
  aStrings.Add('ComponentsConfiguration: ' + fComponentsConfiguration);
  aStrings.Add('CompressedBitsPerSample: ' + fCompressedBitsPerSample);
  aStrings.Add('Compression: ' + fCompression);
  aStrings.Add('Contrast: ' + fContrast);
  aStrings.Add('Copyright: ' + fCopyright);
  aStrings.Add('CustomRendered: ' + fCustomRendered);
  aStrings.Add('DateTime: ' + fDateTime);
  aStrings.Add('DateTimeDigitized: ' + fDateTimeDigitized);
  aStrings.Add('DateTimeOriginal: ' + fDateTimeOriginal);
  aStrings.Add('DefaultCropSize: ' + fDefaultCropSize);
  aStrings.Add('DeviceSettingDescription: ' + fDeviceSettingDescription);
  aStrings.Add('DigitalZoomRatio: ' + fDigitalZoomRatio);
  aStrings.Add('DngVersion: ' + fDngVersion);
  aStrings.Add('ExifVersion: ' + fExifVersion);
  aStrings.Add('ExposureBiasValue: ' + fExposureBiasValue);
  aStrings.Add('ExposureIndex: ' + fExposureIndex);
  aStrings.Add('ExposureMode: ' + fExposureMode);
  aStrings.Add('ExposureProgram: ' + fExposureProgram);
  aStrings.Add('ExposureTime: ' + fExposureTime);
  aStrings.Add('FileSource: ' + fFileSource);
  aStrings.Add('Flash: ' + fFlash);
  aStrings.Add('FlashPixVersion: ' + fFlashPixVersion);
  aStrings.Add('FlashEnergy: ' + fFlashEnergy);
  aStrings.Add('FocalLength: ' + fFocalLength);
  aStrings.Add('FocalLengthIn35mmFilm: ' + fFocalLengthIn35mmFilm);
  aStrings.Add('FocalPlaneResolutionUnit: ' + fFocalPlaneResolutionUnit);
  aStrings.Add('FocalPlaneXResolution: ' + fFocalPlaneXResolution);
  aStrings.Add('FocalPlaneYResolution: ' + fFocalPlaneYResolution);
  aStrings.Add('FNumber: ' + fFNumber);
  aStrings.Add('GainControl: ' + fGainControl);
  aStrings.Add('ImageDescription: ' + fImageDescription);
  aStrings.Add('ImageLength: ' + fImageLength);
  aStrings.Add('ImageUniqueId: ' + fImageUniqueId);
  aStrings.Add('ImageWidth: ' + fImageWidth);
  aStrings.Add('InteroperabilityIndex: ' + fInteroperabilityIndex);
  aStrings.Add('ISO: ' + fISO);
  aStrings.Add('ISOSpeedRatings: ' + fISOSpeedRatings);
  aStrings.Add('JpegInterchangeFormat: ' + fJpegInterchangeFormat);
  aStrings.Add('JpegInterchangeFormatLength: ' + fJpegInterchangeFormatLength);
  aStrings.Add('LightSource: ' + fLightSource);
  aStrings.Add('Make: ' + fMake);
  aStrings.Add('MakerNote: ' + fMakerNote);
  aStrings.Add('MaxApertureValue: ' + fMaxApertureValue);
  aStrings.Add('MeteringMode: ' + fMeteringMode);
  aStrings.Add('Model: ' + fModel);
  aStrings.Add('Oecf: ' + fOecf);
  aStrings.Add('OrfAspectFrame: ' + fOrfAspectFrame);
  aStrings.Add('OrfPreviewImageLength: ' + fOrfPreviewImageLength);
  aStrings.Add('OrfPreviewImageStart: ' + fOrfPreviewImageStart);
  aStrings.Add('OrfThumbnailImage: ' + fOrfThumbnailImage);
  aStrings.Add('Orientation: ' + fOrientation);
  aStrings.Add('PhotometricInterpretation: ' + fPhotometricInterpretation);
  aStrings.Add('PixelXDimension: ' + fPixelXDimension);
  aStrings.Add('PixelYDimension: ' + fPixelYDimension);
  aStrings.Add('PlanarConfiguration: ' + fPlanarConfiguration);
  aStrings.Add('PrimaryChromaticities' + fPrimaryChromaticities);
  aStrings.Add('ReferenceBlackWhite: ' + fReferenceBlackWhite);
  aStrings.Add('RelatedSoundFile: ' + fRelatedSoundFile);
  aStrings.Add('ResolutionUnit: ' + fResolutionUnit);
  aStrings.Add('RowsPerStrip: ' + fRowsPerStrip);
  aStrings.Add('RW2ISO: ' + fRW2ISO);
  aStrings.Add('RW2JpgFromRaw: ' + fRW2JpgFromRaw);
  aStrings.Add('RW2SensorBottomBorder: ' + fRW2SensorBottomBorder);
  aStrings.Add('RW2SensorLeftBorder: ' + fRW2SensorLeftBorder);
  aStrings.Add('RW2SensorRightBorder: ' + fRW2SensorRightBorder);
  aStrings.Add('RW2SensorTopBorder: ' + fRW2SensorTopBorder);
  aStrings.Add('SamplesPerPixel: ' + fSamplesPerPixel);
  aStrings.Add('Saturation: ' + fSaturation);
  aStrings.Add('SceneCaptureType: ' + fSceneCaptureType);
  aStrings.Add('SceneType: ' + fSceneType);
  aStrings.Add('SensingMethod' + fSensingMethod);
  aStrings.Add('Sharpness: ' + fSharpness);
  aStrings.Add('ShutterSpeedValue: ' + fShutterSpeedValue);
  aStrings.Add('Software: ' + fSoftware);
  aStrings.Add('SpatialFrequencyResponse: ' + fSpatialFrequencyResponse);
  aStrings.Add('SubfileType: ' + fSubfileType);
  aStrings.Add('SubjectArea: ' + fSubjectArea);
  aStrings.Add('SubjectDistance: ' + fSubjectDistance);
  aStrings.Add('SubjectDistanceRange: ' + fSubjectDistanceRange);
  aStrings.Add('SubjectLocation: ' + fSubjectLocation);
  aStrings.Add('SubsecTime: ' + fSubsecTime);
  aStrings.Add('SubsecTimeDigitized: ' + fSubsecTimeDigitized);
  aStrings.Add('SubsecTimeOrig: ' + fSubsecTimeOrig);
  aStrings.Add('SubsecTimeDig: ' + fSubsecTimeDig);
  aStrings.Add('SubsecTimeOriginal: ' + fSubsecTimeOriginal);
  aStrings.Add('ThumbnailImageLength: ' + fThumbnailImageLength);
  aStrings.Add('ThumbnailImageWidth: ' + fThumbnailImageWidth);
  aStrings.Add('UserComment: ' + fUserComment);
  aStrings.Add('YCbCrCoefficients: ' + fYCbCrCoefficients);
  aStrings.Add('WhiteBalance: ' + fWhiteBalance);
  aStrings.Add('TransferFunction: ' + fTransferFunction);
  aStrings.Add('WhitePoint: ' + fWhitePoint);
  aStrings.Add('YCbCrPositioning: ' + fYCbCrPositioning);
  aStrings.Add('YCbCrSubSampling: ' + fYCbCrSubSampling);
  aStrings.Add('XResolution' + fXResolution);
  aStrings.Add('YResolution: ' + fYResolution);
  fGPS.LoadToStrings(aStrings);
end;


end.
